Address issues on pythoh/kserve test
ValueError: `detached=False` is no longer supported. In a future release, it will be removed altogether.

Signed-off-by: Spolti <fspolti@redhat.com>